### ISSUE TITLE
JUS-80 모아보기, 히스토리 등에서 화면을 아래로 스크롤 이후에 등록, 메인 페이지 오면 스크롤 된 상태임.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/BlogSyncer#107]
모아보기, 히스토리 등에서 화면을 아래로 스크롤 이후에 등록, 메인 페이지 오면 스크롤 된 상태여서 화면을 위로 계속 스크롤해서 올라가야 함.

**Comment by skywlrl** [comment]
95a7b01b1569d4a0eff24c59753811ec126fa311
* route 변경 시 최상단으로 화면이 보이도록 autoscroll을 true로 설정
