### ISSUE TITLE
JUS-116 블로그 등록의 상세 설정 기능 추가

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/BlogSyncer#172]
http://confluence.wizardfactory.net/pages/viewpage.action?pageId=4325458

**Comment by kimalec** [comment]
provider간의 기본 연결 type을 정리하였습니다.

https://github.com/WizardFactory/BlogSyncer/wiki/provider간의-기본-연결-방법-정리.

![2015-04-27 09 41 20](https://cloud.githubusercontent.com/assets/6895272/7340159/0de413ba-ecc2-11e4-9997-c79ad0ea7150.png)

**Comment by kimalec** [comment]
### skywlrl added a comment - 22/Mar/15 5:31 PM
[작업 진행 방향]
Polygon 모양으로 상세 설정 기능을 지원하려면 Canvas로 그려야 할 것으로 보임
우선 테이블 모양으로 기능 지원을 한 후에 사용자 요구 사항을 파악한 후에 필요한 경우에 진행하기로 함
[Canvas로 작업하는 경우에 참고할 자료]
Drawing regular polygons in javascript canvas
http://scienceprimer.com/drawing-regular-polygons-javascript-canvas
Point Inside A Polygon
http://www.dzone.com/snippets/point-inside-polygon

### skywlrl added a comment - 22/Mar/15 6:21 PM
Icon 주소 변경
* https://www.iconfinder.com/iconsets/miu
### skywlrl added a comment - 05/Apr/15 5:11 PM
* go.js
  * canvas로 다양한 diagram을 지원하는 js이나 유료임
  * http://gojs.net/latest/index.html
* HighCharts
  * General drawing 예제로 ux는 비슷하게 지원은 가능하나 interactive를 지원하지 않는 것으로 보여 사용하지 않음
  * http://www.highcharts.com/demo/renderer
* JointJS
  * free 라이센스로 지원이 가능할 것으로 보여 작업 중
  * http://jointjs.com/

**Comment by kimalec** [comment]
5c58d25d7c9249173d5cf42d94bd4f075268e883
블로그 등록의 상세 설정 기능 추가 
* GroupDB에서 SyncInfo를 찾는 함수 추가
* 상세 설정 화면 추가
  * Blog Id 대신에 title로 표시

e75dd88db7c0ad7e092294d919cbb424f64843f6
블로그 등록의 상세 설정 기능 추가 
* GroupDB에 GroupInfo 추가
* Group 생성 시에 GroupInfo를 Default로 생성 
* 상세 설정 화면 추가
  * Table 스타일로 Cell Click으로 Sync On/Off 변경
  * Table 스타일의 Design 수정 또는 다른 스타일 고려 필요
* 수정된 GroupInfo를 GroupDB에 저

**Comment by skywlrl** [comment]
* Polygons 방식 동작 설명
1. circle 선택
  - 이미 선택된 경우 : 선택 해제
    + circle :  투명
    + line : black
    + marker-source : red(on) / 투명(off)
    + marker-target : red(on) / 투명(off)
  - 선택되지 않은 경우 : 선택
    + circle : lightyellow
2. link 선택
  - circle이 선택되어 있는 경우에만 on/off 상태 변경됨
  - 선택된 circle이 source인 경우
    + line : red(on) / black(off)
    + marker-target : red(on) / 투명(off)
  - 선택된 circle이 target인 경우
    + marker-source : pink(on) / 투명(off)
  - 선택된 circle이 둘 다 아닌 경우
    + line : lightgray
    + marker-source : 투명(on, off)
    + marker-target : 투명(on, off)
* Polygons 방식의 show/hide 처리 문제
  - joint.js에서 최상위 element로 아래와 같이 div가 필요함
    + <div id="paper"></div>
  - 위의 div에 ng-show와 같은 angular.js의 directive를 사용해서 처리하면 타이밍 문제로 동작하지 않음
  - 해결 방법
    + $('#paper').show(); / $('#paper').hide(); 을 사용하면 정상 동작함
    + jquery를 사용하게 되는 문제가 있음(joint.js가 jquery를 사용함)
