### ISSUE TITLE
JUS-120 단어, 문장 보정

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/BlogSyncer#178]
현재 한글, 영어가 썪여 있는 단어, 문장들을 보정하는 작업.

다국어 고려하여 보정하자.

**Comment by kimalec** [comment]
Alec Kim added a comment - 04/Mar/15 10:59 PM
angular.js에서 다국어 처리하기.

Alec Kim added a comment - 04/Mar/15 10:59 PM
backend에서 전달 혹은 생성해서 전달 필요? 아니라면 public에 있어야 하는데 이 경우에 메세지 같이 backend에서 전달하는 메세지는 문제가 생김.
backend/frontend 고민없이 쓸 수 있어어함.

Alec Kim added a comment - 04/Mar/15 11:24 PM - edited
node.js + express + i18n + ejs로 다국어 지원 : http://lky1001.tistory.com/m/post/83
http://i18next.com/ 
그간 다국어처리에 대해 생각하고 고민하던 왠만한 것들은 전부 다 들어가있다. 현재까지 본 것중에는 가장 좋은거 같다. jquery를 이용해 프론트엔드에서 사용할 수 있으며, node.js 를 플랫폼으로 쓰는 경우, 다국어 모듈을 이용해 동일 언어 설정파일을 서버에서도 바로 쓸 수 있다.
(properties 파일을 이용하는 방식은 아니고 json형태의 소스를 쓴다)
자체적으로 쿠키 설정값을 이용할 수 있어서 언어 교체도 URL을 이용해 바로 할 수 있다.

Alec Kim added a comment - 05/Mar/15 12:43 AM
https://github.com/oliversalzburg/i18n-node-angular - use the same resources which I have already generated with i18n-node on my backend.

Alec Kim added a comment - 15/Mar/15 6:24 PM
http://javaworld.co.kr/72 - angular-translate를 이용해서 Angular 앱에 국제화(i18n) 적용하기

Alec Kim added a comment - 19/Mar/15 12:49 AM
mongodb에 저장하여, manager page에서 관리할 수 있고, client에서 get해서 가지고 가서 사용.
error message는 ... 어차피 db에 저장하고 있어서 꺼내서 주는 것도 방법일듯

Alec Kim added a comment - 26/Mar/15 10:13 PM
browser cache도 고려해야 하므로, 파일로 관리하는 것이 좋다고 함.

**Comment by skywlrl** [comment]
* angular-translate 사용법
http://www.ng-newsletter.com/posts/angular-translate.html
