### ISSUE TITLE
error 발생시에 alert window를 띄우고 있는데, 메인화면 상단에 나오게 변경

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/BlogSyncer#235]
error 발생시에 alert window를 띄우고 있는데, 메인화면 상단에 나오게 변경(메뉴바 아래)
박스처리하여 에러내용 표시되고, 오른쪽 끝에 x를 클릭하면 없어지도록 만들기

**Comment by skywlrl** [comment]
Server에서 Error 메시지를 직접 넘겨주는 경우가 있는데 언어에 따라 string 표시를 해주기 위해서 Error type으로 변경해야 함. - #280 이슈 생성함
