### ISSUE TITLE
make robots.txt

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/BlogSyncer#310]
```
10 Jun 2015 03:17:11.010 2015-06-09 18:17:10.740440+00:00 heroku router - - at=info method=GET path="/robots.txt" host=www.justwapps.com request_id=4472911c-ebd6-4a7a-81af-534e4ba7cacb fwd="192.99.107.187/crawl-192-99-107-187.meanpathbot.com" dyno=web.1 connect=0ms service=23ms status=404 bytes=274
10 Jun 2015 03:17:11.027 2015-06-09 18:17:10.723378+00:00 app web.1 - - Error: Not Found : /robots.txt at Layer.handle (/app/app.js:113:15) at trim_prefix 
```
아래와 같은 robots.txt 정보를 만들어야 함.
```javascript
app.get('/robots.txt', function (req, res) {
    res.type('text/plain');
    res.send("User-agent: *\nDisallow: /");
});
```

참고
http://stackoverflow.com/questions/15119760/what-is-the-smartest-way-to-handle-robots-txt-in-express
https://support.google.com/webmasters/answer/6062596?hl=ko&ref_topic=6061961

**Comment by neoqmin** [comment]
https://support.google.com/webmasters/answer/6062608?hl=ko

"사이트에 Google 또는 다른 검색엔진이 색인을 생성하지 않기를 바라는 콘텐츠가 포함되어 있는 경우에만 robots.txt 파일이 필요합니다."

google에 따르면, robots.txt는 검색엔진 크롤러가 액세스하지 않기를 바라는 부분을 정의하는 파일입니다.
