### ISSUE TITLE
plain text posting할때, url에 #이 포함된 경우에 hashtags 넣지 않는 문제.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/BlogSyncer#318]
getHashTags에서 #이 포함되어 있는 경우에 hash tag로 보는데, content에 아래와 같은 url이 포함되어 있는 경우에 잘못 파악할 수 있음.
```
http://www.slidemailapp.com/#tmhmdj:E4Og
```

**Comment by neoqmin** [comment]
문자열에 대해서 replace를 이용하여 처리하기 때문에 문장의 맨처음 #hashtag 인식과 ( /:/,/.){1}#hashtag 인식 두 부분으로 나누어 처리.(add(substr(1))
