### ISSUE TITLE
openshift에 logentries 연동

### ISSUE THREAD

**Issue by neoqmin** [WizardFactory/BlogSyncer#353]
##### logentries 연동

https://github.com/logentries/le_openshift.git 를 소스에 적용

**Comment by neoqmin** [comment]
##### 소스 적용 후 아래와 같이 post_deploy의 속성을 변경해주어야 한다.
$ git update-index --chmod=+x .openshift/action_hooks/*

##### 소스 적용 후 le_config.ini 파일의 ACCOUNT_KEY도 변경해주어야 한다.

**Comment by neoqmin** [comment]
travis의 테스트가 완료된 후 python으로 post_deploy가 자동 실행된다.

**Comment by neoqmin** [comment]
#### rhc ssh --app blogsync로 접속하면, 아래와 같이 openshift vm의 폴더를 볼 수 있다.
##### travis에서 업데이트 되는 repository
cd ${OPENSHIFT_REPO_DIR}
##### post_deploy내에 config 파일이 있는 디렉토리
cd ${OPENSHIFT_DATA_DIR}

**Comment by neoqmin** [comment]
현재 Log Set만 생성되고, 정상적인 로그 출력이 안되는 상황임

**Comment by kimalec** [comment]
post_deploy로 하게 되면, 업데이트 될때마다 생성되기 때문에, 그냥 터미널로 접속하여 le를 설정하고, 실행하는 것이 더 쉽다.

```bash
./le init --account-key=[ACCOUNT-KEY]
./le register --name=blogsync --hostname=blogsync-wzdfac.rhcloud.com
./le follow /var/lib/openshift/55f035ba2d527171d3000173/app-root/logs/nodejs.log
./le monitordeamon
````

이제 logentries에 접속하고 기다리면 메세지 나온다.
https://logentries.com/app/

post_deploy를 제거 하거나, le가 반복하지 않도록 해야 한다.

**Comment by neoqmin** [comment]
다른 개발자들이 작성한 다른 프로젝트와 동일하게 동일한 repository에 logentries 관련 코드를 추가했었으나 blogsync 소스와 같은 repository에 있을 필요가 없는 것 같습니다.

##### blogsync에 포함된 logentries와 관련된 모든 코드를 삭제하는게 좋을 것 같습니다.
##### 의견 부탁드립니다.
