### ISSUE TITLE
slack과 logentries 연동.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/BlogSyncer#359]
logentries에서 error가 발생할때마다, slack blogsync 채널에 메세지를 띄우도록 수정해주세요.

**Comment by neoqmin** [comment]
##### slack에 logentries를 연동하기 위한 준비
1. slack에서 Add Integrations로 Logentires를 위한 #blogsync 채널의 Webhook URL을 생성하고, 복사한다.
2. logentries에서 태그를 생성하고, Associate Logs To Tags로 해당 태그를 연동한다.
3. Add An Alert의 Other Options를 확장해서 Slack을 체크하고, 1에서 생성한 Webhook URL을 붙여넣는다.

**Comment by neoqmin** [comment]
slack에 연동됨을 확인했습니다.

##### 이슈 닫겠습니다.
